name: google_oauth2_client
version: 0.3.1
authors:
- Gerwin Sturm <scarygami@gmail.com>
- Adam Singer <financeCoding@gmail.com>
- Kevin Moore <kevin@thinkpixellab.com>
description: Library to use for Google OAuth2 authentication / Client-side flow
homepage: https://github.com/dart-gde/dart-google-oauth2-library
environment:
  sdk: '>=0.8.1'
dependencies:
  crypto: '>=0.8.1'
  http: '>=0.8.1'
  oauth2: '>=0.8.1'
  path: '>=0.8.1'
dev_dependencies:
  browser: '>=0.8.1'
  hop: '>=0.25.1'
