name:  google_oauth2_client
version: 0.1.0
authors:
- Gerwin Sturm <scarygami@gmail.com>
- Adam Singer <financeCoding@gmail.com>
homepage: https://github.com/dart-gde/dart-google-oauth2-library
description:  Library to use for Google OAuth2 authentication / Client-side flow

dependencies:
  browser: any
  http: 0.3.1+1
  logging: 0.3.1+1