name: google_oauth2_client
version: 0.2.4
authors:
- Gerwin Sturm <scarygami@gmail.com>
- Adam Singer <financeCoding@gmail.com>
description: Library to use for Google OAuth2 authentication / Client-side flow
homepage: https://github.com/dart-gde/dart-google-oauth2-library
dependencies:
  pathos: 0.4.1
  oauth2: 0.4.1
  http: 0.4.1
  browser: any
